apiVersion: v1
kind: ConfigMap
metadata:
  name: config-compartor-config
  labels:
    app: config-compartor
data:
  PORT: "3001"
  NODE_ENV: "production"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-compartor
  labels:
    app: config-compartor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-compartor
  template:
    metadata:
      labels:
        app: config-compartor
    spec:
      containers:
      - name: config-compartor
        image: config-compartor:latest
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: config-compartor-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: config-compartor-config
              key: NODE_ENV
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: config-compartor-service
  labels:
    app: config-compartor
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: config-compartor

---
# Optional: Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: config-compartor-ingress
  labels:
    app: config-compartor
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - config-compartor.yourdomain.com
    secretName: config-compartor-tls
  rules:
  - host: config-compartor.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: config-compartor-service
            port:
              number: 80
